# Generated by Django 5.2.5 on 2025-08-14 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blood_groups',
            },
        ),
        migrations.CreateModel(
            name='CasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'caste_categories',
            },
        ),
        migrations.CreateModel(
            name='GenderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gender_options',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nationalities',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'religions',
            },
        ),
        migrations.CreateModel(
            name='SpecialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'special_categories',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='StudentBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('caste_name', models.CharField(max_length=100)),
                ('place_of_residence', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=10)),
                ('physically_challenged', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('aadhar_encrypted', models.BinaryField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('ews', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.bloodgroup')),
                ('caste_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.castecategory')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.genderoption')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.nationality')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.religion')),
                ('special_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.specialcategory')),
                ('state_of_domicile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.state')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='webapp.studentaccount')),
            ],
            options={
                'db_table': 'student_basic_info',
            },
        ),
    ]
