# Generated by Django 5.2.5 on 2025-08-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_update_residence_choices_and_seed_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasicinfo',
            name='place_of_residence',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Hill', 'Hill')], max_length=10),
        ),
    ]
