# Generated by Django 5.2.5 on 2025-08-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_change_state_of_domicile_to_char_and_seed_special_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_board', models.CharField(max_length=100)),
                ('tenth_school', models.CharField(max_length=150)),
                ('tenth_year', models.IntegerField()),
                ('tenth_roll', models.CharField(max_length=50)),
                ('tenth_marks_obtained', models.FloatField()),
                ('tenth_max_marks', models.FloatField()),
                ('tenth_percentage', models.FloatField()),
                ('twelfth_board', models.CharField(max_length=100)),
                ('twelfth_school', models.CharField(max_length=150)),
                ('twelfth_year', models.IntegerField()),
                ('twelfth_roll', models.CharField(max_length=50)),
                ('twelfth_stream', models.CharField(max_length=20)),
                ('twelfth_marks_obtained', models.FloatField()),
                ('twelfth_max_marks', models.FloatField()),
                ('twelfth_percentage', models.FloatField()),
                ('entrance_exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_exam_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance_exam_score', models.CharField(blank=True, max_length=50, null=True)),
                ('gap_year', models.CharField(max_length=5)),
                ('gap_year_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='webapp.studentaccount')),
            ],
            options={
                'db_table': 'student_academic_info',
            },
        ),
    ]
