# Generated by Django 5.2.5 on 2025-08-19 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_studentacademicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_board', models.CharField(max_length=200)),
                ('tenth_school', models.CharField(max_length=250)),
                ('tenth_year', models.PositiveIntegerField()),
                ('tenth_roll', models.CharField(max_length=50)),
                ('tenth_marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tenth_max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_board', models.CharField(max_length=200)),
                ('twelfth_school', models.CharField(max_length=250)),
                ('twelfth_year', models.PositiveIntegerField()),
                ('twelfth_roll', models.CharField(max_length=50)),
                ('twelfth_stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Other', 'Other')], max_length=20)),
                ('twelfth_marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('twelfth_max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entrance_exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entrance_exam_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance_exam_score', models.CharField(blank=True, max_length=50, null=True)),
                ('gap_year', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('gap_year_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previous_academic', to='webapp.studentaccount')),
            ],
            options={
                'db_table': 'student_previous_academic_info',
            },
        ),
        migrations.DeleteModel(
            name='StudentAcademicInfo',
        ),
    ]
