# Generated by Django 5.2.5 on 2025-08-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_previousacademicinfo_delete_studentacademicinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='previousacademicinfo',
            table='student_academic_info',
        ),
    ]
